// <auto-generated />
using DataAccess_CMSProject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess_CMSProject.Migrations
{
    [DbContext(typeof(CMSDBContext))]
    [Migration("20210609202908_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataAccess_CMSProject.DataModels.BannerImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.HasKey("ImageId");

                    b.HasIndex("PageId");

                    b.ToTable("BannerImages");
                });

            modelBuilder.Entity("DataAccess_CMSProject.DataModels.Content", b =>
                {
                    b.Property<int>("ContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContentId");

                    b.HasIndex("PageId")
                        .IsUnique();

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("DataAccess_CMSProject.DataModels.Footer", b =>
                {
                    b.Property<int>("FooterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HtmlText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FooterId");

                    b.ToTable("Footers");
                });

            modelBuilder.Entity("DataAccess_CMSProject.DataModels.Header", b =>
                {
                    b.Property<int>("HeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HtmlText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.HasKey("HeaderId");

                    b.HasIndex("PageId")
                        .IsUnique();

                    b.ToTable("Headers");
                });

            modelBuilder.Entity("DataAccess_CMSProject.DataModels.Pages", b =>
                {
                    b.Property<int>("PageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PageLink")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PageId");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("DataAccess_CMSProject.DataModels.Title", b =>
                {
                    b.Property<int>("TitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TitleId");

                    b.HasIndex("PageId")
                        .IsUnique();

                    b.ToTable("Titles");
                });

            modelBuilder.Entity("DataAccess_CMSProject.DataModels.BannerImage", b =>
                {
                    b.HasOne("DataAccess_CMSProject.DataModels.Pages", "Pages")
                        .WithMany("Images")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pages");
                });

            modelBuilder.Entity("DataAccess_CMSProject.DataModels.Content", b =>
                {
                    b.HasOne("DataAccess_CMSProject.DataModels.Pages", "Pages")
                        .WithOne("Content")
                        .HasForeignKey("DataAccess_CMSProject.DataModels.Content", "PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pages");
                });

            modelBuilder.Entity("DataAccess_CMSProject.DataModels.Header", b =>
                {
                    b.HasOne("DataAccess_CMSProject.DataModels.Pages", "Pages")
                        .WithOne("Header")
                        .HasForeignKey("DataAccess_CMSProject.DataModels.Header", "PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pages");
                });

            modelBuilder.Entity("DataAccess_CMSProject.DataModels.Title", b =>
                {
                    b.HasOne("DataAccess_CMSProject.DataModels.Pages", "Pages")
                        .WithOne("Title")
                        .HasForeignKey("DataAccess_CMSProject.DataModels.Title", "PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pages");
                });

            modelBuilder.Entity("DataAccess_CMSProject.DataModels.Pages", b =>
                {
                    b.Navigation("Content");

                    b.Navigation("Header");

                    b.Navigation("Images");

                    b.Navigation("Title");
                });
#pragma warning restore 612, 618
        }
    }
}
